---

all:
  children:

    network:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_user: admin
        ansible_password: enterprise

      children:
        # --- ISP ---
        isp:
          children:
            isp_l3switches:
              hosts:
                ISP-L3S-01:
                  ansible_host: 10.48.64.1
                # ISP-L3S: -02, -03 IP Addresses
                ISP-L3S-02:
                ISP-L3S-03:
                ISP-L3S-04:
                  ansible_host: 10.48.64.5
            isp_l2switches:
              hosts:
                ISP-L2S-01:

        # --- North America ---
        na:
          children:
            na_routers:
              hosts:
                NA-BR-01:
                  ansible_host: 10.48.65.1
                NA-BR-02:
                  ansible_host: 10.48.65.5
                NA-R-01:
                  ansible_host: 10.48.65.18
                NA-SOHOR-01:
                  ansible_host: 10.48.65.10
            na_l3switches:
              hosts:
                NA-L3S-01:
                  ansible_host: 10.48.10.2
                NA-L3S-02:
                  ansible_host: 10.48.10.3
            na_l2switches:
              # No SVI
              hosts:
                NA-L2S-01:
                NA-L2S-02:
                NA-L2S-03:

    virtualization:
      vars:
        ansible_connection: ssh
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3

      children:
        proxmox:
          hosts: {}

    windows:
      vars:
        ansible_connection: winrm
        ansible_port: 5986
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore

      children:
        ad:
          hosts: {}

    routers:
      children:
        na_routers:

    l3switches:
      children:
        isp_l3switches:
        na_l3switches:

    l2switches:
      children:
        isp_l2switches:
        na_l2switches:
